package com.xumtech.chatbot.service;

import com.xumtech.chatbot.dto.ChatRequest;
import com.xumtech.chatbot.dto.ChatResponse;

/**
 * Defines the contract for the chatbot's business logic.
 * Any class implementing this interface must be able to process a user message.
 */
public interface IChatService {

    /**
     * Processes the incoming user message and returns an appropriate response.
     *
     * @param request The DTO containing the user's message.
     * @return A DTO with the response generated by the bot.
     */
    ChatResponse processMessage(ChatRequest request);
}